theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - test1.md
  - test2.md
  - docs/test1.md
  - docs/test2.md
